<?php include 'basics.php'; ?>
<?php include 'header.php'; ?>
<?php include 'navbar.php'; ?>
<?php include 'content.php'; ?>
<?php include 'modal1.php'; ?>
<?php include 'modal2.php'; ?>
<?php include 'modal3.php'; ?>
<?php include 'textvars.php'; ?>
<?php include 'footer.php'; ?>